---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: rolling
  name: rolling
  namespace: vshn-kubernetes-ha-edu
spec:
  output:
    to:
      kind: ImageStreamTag
      name: rolling:latest
  runPolicy: Serial
  source:
    git:
      ref: main
      uri: git@github.com:a-Tell/kubernetes-ha-edu.git
    contextDir: rollout_strategies/htdocs/rolling
    sourceSecret:
      name: deploy-test
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: httpd:2.4-el8
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
  - github:
      secret: LTNgwWa4qF8QYih2kcNlFwdLey0MdL5gssidm6uL
    type: GitHub
  - generic:
      secret: qsJ8yKDmGK1wfjyyHcBaRj5mCOHL62h1RfqY7VhM
    type: Generic
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: rolling
  name: rolling
  namespace: vshn-kubernetes-ha-edu
spec:
  replicas: 5
  selector:
    app: rolling
  template:
    metadata:
      labels:
        app: rolling
      name: rolling
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/vshn-kubernetes-ha-edu/rolling
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        name: httpd
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - httpd
      from:
        kind: ImageStreamTag
        name: rolling:latest
        namespace: vshn-kubernetes-ha-edu
      lastTriggeredImage: image-registry.openshift-image-registry.svc:5000/vshn-kubernetes-ha-edu/rolling
    type: ImageChange
  - type: ConfigChange
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rolling
  name: rolling
  namespace: vshn-kubernetes-ha-edu
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: rolling
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: rolling
  name: rolling
  namespace: vshn-kubernetes-ha-edu
spec:
  host: rolling-vshn-kubernetes-ha-edu.apps.cloudscale-lpg-2.appuio.cloud
  to:
    kind: Service
    name: rolling
    weight: 100
  wildcardPolicy: None
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: rolling
  name: rolling
  namespace: vshn-kubernetes-ha-edu
spec:
  lookupPolicy:
    local: false
