apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rolling
  namespace: vshn-kubernetes-ha-edu
  labels:
    app: nginx-rolling
spec:
  replicas: 3
  strategy:
        type: RollingUpdate
  selector:
    matchLabels:
      app: nginx-rolling
  template:
    metadata:
      labels:
        app: nginx-rolling
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-rolling
  namespace: vshn-kubernetes-ha-edu
spec:
  selector:
    app: nginx-rolling 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
